apiVersion: bkauf.com/v1
kind: cluster
metadata:
  name: c-team
  labels:
    cluster-owner: bkauf
spec:
  compositionRef:
    # Possible values cluster-gcp, cluster-azure, cluster-aws
    name: cluster-azure
  parameters:
    # Possible values small, medium, large
    nodeSize: medium
   # version: "1.22"
    minNodeCount: 2
  writeConnectionSecretToRef:
    namespace: c-team
    name: cluster