# root-sync.yaml
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: crossplane
  namespace: config-management-system
spec:
  sourceType: git
  sourceFormat: hierarchy
  git:
    repo: https://github.com/bkauf/anthos-crossplane-demo
    auth: none
    dir: crossplane-acm
    branch: master