apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  name: cluster-1 # edit to match cluster name
  annotations:
    crossplane.io/external-name: cluster-1 # edit to match cluster name
spec:
  providerConfigRef: 
    name: default-gcp # edit to match GCP providerconfig
  forProvider:
    location: us-central1-c # edit to match desired location
    minMasterVersion: 1.24.11-gke.1000 # edit to match desired version
    nodeVersion: 1.24.11-gke.1000 # edit to match desired version
