apiVersion: gcp.gke.cloud.google.com/v1beta1
kind: ProviderConfig
metadata:
  name: default-gcp
spec:
  projectID: anthos-multi-cloud-335819
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-config
      name: gcp-creds
      key: creds