apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: test-cluster
  annotations:
    crossplane.io/external-name: test-cluster
spec:
      forProvider:
        location: us-central1-c
        masterAuth:
          username:
        #releaseChannel:
        #  channel: RAPID
      providerConfigRef:
        name: default
---
apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: test-cluster
  annotations:
    crossplane.io/external-name: default-pool
spec:
  forProvider:
    clusterRef: 
      name: test-cluster
    locations:
    - us-central1-c
  providerConfigRef:
        name: default