apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-node-pool
  labels:
    crossplane.io/xrd: compositenodepools.demo.anthos.com
    provider: gcp
    cluster: gke
spec:
  compositeTypeRef:
    apiVersion: demo.anthos.com/v1
    kind:  CompositeNodepool
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: nodepool
    base:
      apiVersion: container.gcp.crossplane.io/v1beta1
      kind: NodePool
      spec:
        providerConfigRef:
          name: default-gcp
        forProvider:
          clusterRef:
            name: test-cluster
          config:
            machineType: n1-standard-1
            diskSizeGb: 120
            diskType: pd-ssd
            imageType: cos_containerd
            labels:
              test-label: crossplane-created
            oauthScopes:
            - "https://www.googleapis.com/auth/devstorage.read_only"
            - "https://www.googleapis.com/auth/logging.write"
            - "https://www.googleapis.com/auth/monitoring"
            - "https://www.googleapis.com/auth/servicecontrol"
            - "https://www.googleapis.com/auth/service.management.readonly"
            - "https://www.googleapis.com/auth/trace.append"      
          initialNodeCount: 3
          locations:
            - "us-east1-b"
    patches:
    - fromFieldPath: spec.parameters.clusterName
      toFieldPath: spec.forProvider.clusterRef.name
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.forProvider.config.machineType
      transforms:
        - type: map
          map:
            small: e2-small
            medium: e2-medium
            large: e2-standard-2
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.status
      toFieldPath: status.nodePoolStatus
    readinessChecks:
    - type: MatchString
      fieldPath: status.atProvider.status
      matchString: ACTIVE
 
